version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Replace with your actual Render PostgreSQL database URL
      - DATABASE_URL=postgresql://cogni_ml_user:YHOoLk1F8aHxgTxODkEcYD9FOhQEFdq7@dpg-d2s21bripnbc73e56o4g-a.oregon-postgres.render.com/cogni_ml
      - USE_SQLITE=false
      - PORT=8000
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s