services:
  - type: web
    name: loan-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgresql://cogni_ml_user:YHOoLk1F8aHxgTxODkEcYD9FOhQEFdq7@dpg-d2s21bripnbc73e56o4g-a.oregon-postgres.render.com/cogni_ml"
      - key: USE_SQLITE
        value: "false"
      - key: PORT
        value: "8000"
    healthCheckPath: /health
