services:
  - type: web
    name: loan-api
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r Requirements.txt"

    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loan-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: USE_SQLITE
        value: "false"

databases:
  - name: loan-db
    databaseName: loan_system
    plan: free
